language: generic
dist: xenial

branches:
  only:
    - master

matrix:
  include:
    - os: linux
      arch: amd64
      compiler: g++
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - libpq-dev
      env:
        - CXX=g++-9 BUILD=Release
before_install:
  - CXX=g++-9 BUILD=Release
  - sudo rm /usr/bin/g++
  - sudo ln -s /usr/bin/g++-9 /usr/bin/g++
  - g++ --version
  - >
    if ! test -f boost_1_72_0; then
        wget https://sourceforge.net/projects/boost/files/boost/1.72.0/boost_1_72_0.tar.gz;
        tar -xzvf boost_1_72_0.tar.gz >/dev/null;
        cd boost_1_72_0;
        sudo ./bootstrap.sh --prefix=/usr/local --with-libraries=all;
        sudo ./b2 -j16 install;
        sudo /bin/bash -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/boost.conf';
        sudo ldconfig;
        cd ..;
    fi;
cache: boost_1_72_0
script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - mkdir -p build
     - cd build
     - cmake .. 
     - make
     - make RunTests
     
